name: run-train

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run train script
      run: python train.py
      
    - name: Archive plots
      uses: actions/upload-artifact@v2
      with:
        name: plots
        path: |
          feature_importance.png
          residuals.png

    - name: Download plots
      uses: actions/download-artifact@v4.1.1
      with:
        name: plots
